-- ----------------------------
--  Table structure for `spring_cloud_health_a`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_a`;
CREATE TABLE `spring_cloud_health_a` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_b`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_b`;
CREATE TABLE `spring_cloud_health_b` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_c`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_c`;
CREATE TABLE `spring_cloud_health_c` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_d`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_d`;
CREATE TABLE `spring_cloud_health_d` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_e`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_e`;
CREATE TABLE `spring_cloud_health_e` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_f`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_f`;
CREATE TABLE `spring_cloud_health_f` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_g`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_g`;
CREATE TABLE `spring_cloud_health_g` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_h`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_h`;
CREATE TABLE `spring_cloud_health_h` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_i`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_i`;
CREATE TABLE `spring_cloud_health_i` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_j`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_j`;
CREATE TABLE `spring_cloud_health_j` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_k`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_k`;
CREATE TABLE `spring_cloud_health_k` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_l`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_l`;
CREATE TABLE `spring_cloud_health_l` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_m`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_m`;
CREATE TABLE `spring_cloud_health_m` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_n`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_n`;
CREATE TABLE `spring_cloud_health_n` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_o`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_o`;
CREATE TABLE `spring_cloud_health_o` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_p`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_p`;
CREATE TABLE `spring_cloud_health_p` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_q`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_q`;
CREATE TABLE `spring_cloud_health_q` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_r`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_r`;
CREATE TABLE `spring_cloud_health_r` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_s`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_s`;
CREATE TABLE `spring_cloud_health_s` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_t`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_t`;
CREATE TABLE `spring_cloud_health_t` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_u`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_u`;
CREATE TABLE `spring_cloud_health_u` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_v`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_v`;
CREATE TABLE `spring_cloud_health_v` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_w`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_w`;
CREATE TABLE `spring_cloud_health_w` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_x`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_x`;
CREATE TABLE `spring_cloud_health_x` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_y`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_y`;
CREATE TABLE `spring_cloud_health_y` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `spring_cloud_health_z`
-- ----------------------------
DROP TABLE IF EXISTS `spring_cloud_health_z`;
CREATE TABLE `spring_cloud_health_z` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键ID',
    `application_name` varchar(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    `server_host` varchar(15) NOT NULL DEFAULT '' COMMENT '主机名',
    `server_port` varchar(15) NOT NULL DEFAULT '' COMMENT '端口号',
    `processors` tinyint(5) unsigned NOT NULL DEFAULT 0 COMMENT '处理器数量',
    `mem` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '分配给应用的总内存数',
    `mem_free` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '当前空闲的内存数量',
    `instance_uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `uptime` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '运行时间',
    `systemload_average` float(5,2) unsigned NOT NULL DEFAULT 0.00 COMMENT '系统平均负载',
    `heap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已提交堆内内存大小',
    `heap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆内内存大小',
    `heap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆内内存大小',
    `heap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆内内存大小',
    `nonheap_committed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外存已提交大小',
    `nonheap_init` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM初始化堆外内存大小',
    `nonheap_used` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM已使用堆外内存大小',
    `nonheap` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'JVM堆外内存大小',
    `threads_peak` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程峰值',
    `threads_daemon` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '守护线程数',
    `threads_totalstarted` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程总启动数',
    `threads` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '线程数',
    `classes` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '全部类',
    `classes_loaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已加载类',
    `classes_unloaded` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '已卸载类',
    `gc_scavenge_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收次数',
    `gc_scavenge_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '垃圾回收消耗时间',
    `gc_marksweep_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法次数',
    `gc_marksweep_time` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '标记清除算法时间',
    `httpsessions_max` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP最大会话数',
    `httpsessions_active` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'HTTP活跃会话数',
    `created_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '当前日期',
    PRIMARY KEY (`id`),
    KEY `idx_application_time` (`application_name`,`created_time`),
    KEY `idx_application_host_port_time` (`application_name`,`server_host`,`server_port`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
